CREATE DATABASE PD_311_Academy_DDL
ON 
(
	NAME = N'PD_311_Academy_DLL',
	FILENAME = N'E:\Programs\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PD_311_Academy_DLL.mdf',
	SIZE = 8MB, MAXSIZE = 512MB, FILEGROWTH = 8MB
)
LOG ON
(
	NAME = N'PD_311_Academy_DLL_log',
	FILENAME = N'E:\Programs\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PD_311_Academy_DLL_log.ldf',
	SIZE = 8MB, MAXSIZE = 512MB, FILEGROWTH = 8MB
);