USE PD311_AcademyDesign;
GO

INSERT Subjects
	(subject_name, amount_of_hours, report_type_id)
VALUES
	(N'Процедурное программирование на языке C++', 96, 1),
	(N'Объектно-ориентированное программирование на языке C++', 76, 1),
	(N'UML и паттерны проектирования', 18, 2),
	(N'Платформа .NET и язык программирования C#', 32, 1),
	(N'Разработка Windows приложений на языке C++', 18, 1),
	(N'Разработка Windows приложений на языке C#', 18, 1),
	(N'Теория баз данных и программирование MS_MSL Server', 24, 1),
	(N'Технология доступа к данных ADO.NET', 24, 1),
	(N'Разработка Web-приложений с использованием технологии ASP.NET', 48, 1),
	(N'Основы программирования на языке Java', 96, 1),
	(N'Разработка Back-End приложений на языке Java', 50, 1),
	(N'HTML/CSS', 24, 1),
	(N'Програмирование на языке JavaScript', 24, 1),
	(N'Теория баз данных и программирование MySQL Server', 32, 1),
	(N'Back-End разработка на языке PHP', 24, 1),
	(N'Front-End разработка с использованием NodeJS', 24, 1),
	(N'Back-End разработка с использованием ReactJS', 24, 1),
	(N'Adobe Photoshop', 32, 1),
	(N'Adobe Illustrator', 32, 1),
	(N'Adobe Premiere Pro', 32, 1),
	(N'Adobe After Effects', 48, 1),
	(N'AutoCAD', 96, 1),
	(N'3DS Max', 32, 1),
	(N'Maya', 32, 1),
	(N'Blender', 32, 1),
	(N'Базовые технологии локальных сетей', 24, 2),
	(N'Маршрутизация в IP-сетях', 48, 1),
	(N'Протоколы прикладного уровня', 48, 1),
	(N'Hardware PC', 32, 1),
	(N'Администрирование Windows XP/7/8/10/11', 32, 1),
	(N'Администрирование Windows Server', 96, 1),
	(N'Администрирование UNIX', 96, 1),
	(N'Game Development на движке CryEngine', 78, 1),
	(N'Game Development на движке UnrealEngine', 48, 1),
	(N'Android Development', 96, 1)
